### ISSUE TITLE
How to have multiple fields in one row?

### ISSUE THREAD

**Issue by fbingha** [nibri10/nova-grid#1]
Adding the size option to my fields does make them smaller but they remain on individual rows.

**Comment by nibri10** [comment]
I have future ideas to add this. @fbingha

**Comment by fbingha** [comment]
Isn't the whole reason for this package is to have multiple fields in one row? The package that you took this from shows multiple fields on one row.

**Comment by nibri10** [comment]
this is working perfectly this way, what will be a future release will be deployment of tables in it

**Comment by nibri10** [comment]
There are some things that I want to improve, but I have no time @fbingha

**Comment by fbingha** [comment]
Okay, perhaps some other package I installed is interfering because I just have the fields stacking up, not inline in one row.

**Comment by nibri10** [comment]
Are you using the -> size ('w-1/3') argument for example? In the field?

**Comment by fbingha** [comment]
Yes, I placed that on the first three columns.

![image](https://user-images.githubusercontent.com/2914520/67887669-f88fe200-fb08-11e9-836e-71db2f137b8e.png)

**Comment by nibri10** [comment]
In NovaServiceProvider.php importing my package?

**Comment by nibri10** [comment]
Send code our resource

**Comment by fbingha** [comment]
Yes I import your package in NovaServiceProvider

If I didn't do that then the fields wouldn't be shrinking to 1/3, which you can see that they do in my screenshot,

**Comment by nibri10** [comment]
try to put a smaller value for example is -1 / 6

**Comment by nibri10** [comment]
Version using in laravel nova ?
Version Laravel?

**Comment by fbingha** [comment]
It's not a problem with 1/3 vs 1/6 as my window is wide. Laravel 5.8 Nova 2.4

**Comment by nibri10** [comment]
I am using I Laravel 6* and Laravel NOVA 2.5.6 testing https://raw.githubusercontent.com/nibri10/sistema-financeira-nova/master/app/Nova/Status.php?token=AFL5N5OLHNIP7ZAY6JAGLQK5YMLVE

**Comment by picrenan** [comment]
@fbingha 

I have this same problem, but I used nova panel to fix it temporally.

https://nova.laravel.com/docs/2.0/resources/fields.html#showing-hiding-fields

```
new Panel('Biografia', [
      Text::make('Bio Português', 'bio_pt')
          ->hideFromIndex()
          ->size('w-1/3'),

     Text::make('Bio Inglês', 'bio_en')
          ->hideFromIndex()
          ->size('w-1/3'),

    Text::make('Bio Espanhol', 'bio_es')
        ->hideFromIndex()
        ->size('w-1/3'),
]),
```

**Comment by felixmFlow** [comment]
I tried using panel but it didn't work.
I'm using Laravel 8 and nova 3.
Did anyone come right with an alternative solution please?
