### ISSUE TITLE
error when i use Eminiarts\Tabs and nibri10 / nova-grid

### ISSUE THREAD

**Issue by loveyuxiao** [nibri10/nova-grid#10]
error when i use Eminiarts\Tabs and nibri10 / nova-grid

**Comment by antlusher** [comment]
@loveyuxiao whats the error?

**Comment by issour** [comment]
Hi,
Same issue here  the error is : 
TypeError: Cannot read property 'add' of undefined
    at a.mounted (nova-grid:1)

Many Thx !
