### ISSUE TITLE
Grid doesn't work on index

### ISSUE THREAD

**Issue by Zen0x7** [nibri10/nova-grid#2]
Hi @nibri10,

Your package works great, the grids helps much on create/update views. But this doesn't work on details view.

:/

**Comment by nibri10** [comment]
Only update/created in resources

**Comment by nibri10** [comment]
Index don't working and showing information

**Comment by Zen0x7** [comment]
Well, i make some package to solve in details grid. 

https://github.com/demency/nova-gridder

🎉🎉🎉
