### ISSUE TITLE
not work in nova 2.7.0

### ISSUE THREAD

**Issue by loveyuxiao** [nibri10/nova-grid#4]
not work in nova 2.7.0

**Comment by nibri10** [comment]
Please describe error message em Laravel NOVA 2.7.0 @loveyuxiao

**Comment by nibri10** [comment]
![image](https://user-images.githubusercontent.com/22533877/68764848-3d804200-05fa-11ea-9cc4-3cb6bb2bb7a1.png)
### **Working normally in Laravel Nova version 2.7.0**

### After the new upgrade nova  run these commands @loveyuxiao 

- php artisan cache:clear;
- php artisan config:clear;
- php artisan route:clear;
- php artisan view:clear;
- php artisan clear-compiled;
- composer dump-autoload;
- php artisan config:cache;
- php artisan route:cache;
- php artisan view:cache;
